<?php

declare(strict_types=1);

namespace Tests\Models\Courier;

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;
use Myth\Courier\Enums\ContactStatus;
use Myth\Courier\Models\ContactModel;

/**
 * @internal
 */
final class ContactModelTest extends CIUnitTestCase
{
    use DatabaseTestTrait;

    protected $refresh   = true;
    protected $namespace = 'Myth\Courier';

    public function testTokenIsAutoGeneratedOnInsert(): void
    {
        $model = new ContactModel();
        $id    = $model->insert(['email' => 'test@example.com']);

        $contact = $model->find($id);

        $this->assertNotEmpty($contact->unsubscribe_token);
        $this->assertSame(64, strlen($contact->unsubscribe_token));
    }

    public function testExistingTokenIsPreservedOnInsert(): void
    {
        $model = new ContactModel();
        $token = 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2';
        $id    = $model->insert(['email' => 'test2@example.com', 'unsubscribe_token' => $token]);

        $contact = $model->find($id);

        $this->assertSame($token, $contact->unsubscribe_token);
    }

    public function testDuplicateEmailIsRejected(): void
    {
        $model = new ContactModel();
        $model->insert(['email' => 'dupe@example.com']);

        $result = $model->insert(['email' => 'dupe@example.com']);

        $this->assertFalse($result);
    }

    public function testSubscribedScopeReturnsOnlySubscribedContacts(): void
    {
        $model = new ContactModel();
        $model->insert(['email' => 'sub@example.com', 'status' => ContactStatus::Subscribed]);
        $model->insert(['email' => 'unsub@example.com', 'status' => ContactStatus::Unsubscribed]);

        $results = $model->subscribed()->findAll();

        $this->assertCount(1, $results);
        $this->assertSame('sub@example.com', $results[0]->email);
    }
}
